config/routes.rb
Rails.application.routes.draw do
  resources :flowers

  resources :baghs

  root 'baghs#index'

end

app/models/bagh.rb
class Bagh < ActiveRecord::Base
    has_many :flowers
end

app/models/flower.rb
class Flower < ActiveRecord::Base
    belongs_to :bagh
    validates :content, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baghs_controller.rb
class BaghsController < ApplicationController
  before_action :set_bagh, only: [:show, :edit, :update, :destroy]

  # GET /baghs
  # GET /baghs.json
  def index
    @baghs = Bagh.all
  end

  # GET /baghs/1
  # GET /baghs/1.json
  def show
  end

  # GET /baghs/new
  def new
    @bagh = Bagh.new
  end

  # GET /baghs/1/edit
  def edit
  end

  # POST /baghs
  # POST /baghs.json
  def create
    @bagh = Bagh.new(bagh_params)

    respond_to do |format|
      if @bagh.save
        format.html { redirect_to @bagh, notice: 'Bagh was successfully created.' }
        format.json { render :show, status: :created, location: @bagh }
      else
        format.html { render :new }
        format.json { render json: @bagh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baghs/1
  # PATCH/PUT /baghs/1.json
  def update
    respond_to do |format|
      if @bagh.update(bagh_params)
        format.html { redirect_to @bagh, notice: 'Bagh was successfully updated.' }
        format.json { render :show, status: :ok, location: @bagh }
      else
        format.html { render :edit }
        format.json { render json: @bagh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baghs/1
  # DELETE /baghs/1.json
  def destroy
    @bagh.destroy
    respond_to do |format|
      format.html { redirect_to baghs_url, notice: 'Bagh was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bagh
      @bagh = Bagh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bagh_params
      params.require(:bagh).permit(:name, :address)
    end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

  # GET /flowers
  # GET /flowers.json
  def index
    @flowers = Flower.all
  end

  # GET /flowers/1
  # GET /flowers/1.json
  def show
  end

  # GET /flowers/new
  def new
    @flower = Flower.new
  end

  # GET /flowers/1/edit
  def edit
  end

  # POST /flowers
  # POST /flowers.json
  def create
    @flower = Flower.new(flower_params)

    respond_to do |format|
      if @flower.save
        format.html { redirect_to @flower, notice: 'Flower was successfully created.' }
        format.json { render :show, status: :created, location: @flower }
      else
        format.html { render :new }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flowers/1
  # PATCH/PUT /flowers/1.json
  def update
    respond_to do |format|
      if @flower.update(flower_params)
        format.html { redirect_to @flower, notice: 'Flower was successfully updated.' }
        format.json { render :show, status: :ok, location: @flower }
      else
        format.html { render :edit }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1
  # DELETE /flowers/1.json
  def destroy
    @flower.destroy
    respond_to do |format|
      format.html { redirect_to flowers_url, notice: 'Flower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flower
      @flower = Flower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flower_params
      params.require(:flower).permit(:content, :bagh_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baghs_helper.rb
module BaghsHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/baghs/_form.html.erb
<%= form_for(@bagh) do |f| %>
  <% if @bagh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bagh.errors.count, "error") %> prohibited this bagh from being saved:</h2>

      <ul>
      <% @bagh.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baghs/edit.html.erb
<h1>Editing Bagh</h1>

<%= render 'form' %>

<%= link_to 'Show', @bagh %> |
<%= link_to 'Back', baghs_path %>

app/views/baghs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Baghs</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baghs.each do |bagh| %>
      <tr>
        <td><%= bagh.name %></td>
        <td><%= bagh.address %></td>
        <td><%= link_to 'Show', bagh %></td>
        <td><%= link_to 'Edit', edit_bagh_path(bagh) %></td>
        <td><%= link_to 'Destroy', bagh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<botton>
  <%= link_to 'New Bagh', new_bagh_path %>  
</botton>

app/views/baghs/new.html.erb
<h1>New Bagh</h1>

<%= render 'form' %>

<%= link_to 'Back', baghs_path %>

app/views/baghs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bagh.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @bagh.address %>
</p>

<%= link_to 'Edit', edit_bagh_path(@bagh) %> |
<%= link_to 'Back', baghs_path %>

app/views/flowers/_form.html.erb
<%= form_for(@flower) do |f| %>
  <% if @flower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flower.errors.count, "error") %> prohibited this flower from being saved:</h2>

      <ul>
      <% @flower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :bagh_id %><br>
    <%= f.number_field :bagh_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h1>Editing Flower</h1>

<%= render 'form' %>

<%= link_to 'Show', @flower %> |
<%= link_to 'Back', flowers_path %>

app/views/flowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flowers</h1>

<table border="1">
  <thead>
    <tr>
      <th>Content</th>
      <th>Bagh</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flowers.each do |flower| %>
      <tr>
        <td><%= flower.content %></td>
        <td><%= flower.bagh_id %></td>
        <td><%= link_to 'Show', flower %></td>
        <td><%= link_to 'Edit', edit_flower_path(flower) %></td>
        <td><%= link_to 'Destroy', flower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flower', new_flower_path %>

app/views/flowers/new.html.erb
<h1>New Flower</h1>

<%= render 'form' %>

<%= link_to 'Back', flowers_path %>

app/views/flowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @flower.content %>
</p>

<p>
  <strong>Bagh:</strong>
  <%= @flower.bagh_id %>
</p>

<%= link_to 'Edit', edit_flower_path(@flower) %> |
<%= link_to 'Back', flowers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GardenApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>